
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stepsifi_api_development

test:
  <<: *default
  database: stepsifi_api_test

production:
  <<: *default
  database: stepsifi_api_production
  url: <%= ENV[‘DATABASE_URL’] %>
  username: stepsifi_api
  password: <%= ENV['STEPSIFI_API_DATABASE_PASSWORD'] %>
